# Pentagonal numbers are generated by the formula, 
# P(n) = n * (3n − 1) / 2. 
# The first ten pentagonal numbers are: 
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). 
# However, their difference,70 − 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, P(j) and P(k), 
# for which their sum and difference are pentagonal and 
# D = |P(k) − P(j)| is minimised; what is the value of D?
#___________________________________________________________

def pentagonal(n):
    return n * (3 * n - 1) // 2

def generate_pentagons(n):
    pentagons = []
    for i in range(1, n + 1):
        pentagons.append(pentagonal(i))
    return pentagons

def pent(n):
    pentagons = set(generate_pentagons(n))
    for j in pentagons:
        for k in pentagons:
            if j > k:
                continue
            if j + k in pentagons and abs(k - j) in pentagons:
                return abs(j - k)
    return False

print(pent(10 ** 4))