# Triangle, pentagonal, and hexagonal numbers are generated by 
# the following formulas:
# Triangle    T(n) = n * (n+1)/2     1, 3, 6, 10, 15, ...
# Pentagonal  P(n) = n * (3n−1)/2    1, 5, 12, 22, 35, ...
# Hexagonal   H(n) = n * (2n−1)      1, 6, 15, 28, 45, ...
# It can be verified that T(285) = P(165) = H(143) = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
#_____________________________________________________________________
import math

def tri(n):
    return n * (n + 1) // 2

def pen(P):
    return (1 + math.sqrt(1 + 24 * P)) / 6

def heks(H):
    return (1 + math.sqrt(1 + 8 * H)) / 4

n = 286
while True:
    T = tri(n)
    if pen(T) == int(pen(T)) and heks(T) == int(heks(T)):
        print(T)
        break
    n += 1